language: csharp
solution: Secure.SecurityDatabaseSync.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - dotnet restore
    - dotnet build
    - dotnet test SecurityDatabaseSync.Tests/SecurityDatabaseSync.Tests.csproj